### ISSUE TITLE
Add support for PUT /tools/{id}/versions/{version} endpoint.

### ISSUE THREAD

**Issue by kushagra189** [elixir-cloud-aai/trs-filer#34]
* Required to replace (if exists) or create (if it does not exist) a version with a specific user-defined ID to an existing tool.
* Add required specs in the additional API spec list.
* Implement the endpoint and corresponding tests.

Please refer PINNED comment on slack channel for scope.

**Comment by uniqueg** [comment]
The functionality to create or replace is implemented in the `POST` endpoint. While this implementation is somewhat in contrast to usually expected behavior for `POST` in "REST" API behavior, it will cover our use cases just fine for now. As the version ID field is currently part of the `RegisterToolVersion` schema, the schema couldn't be used for a `PUT` endpoint, so a proper implementation (`POST` will create an ID for the user; `POST` will allow the user to define the ID) will require removing the `id` property from the schema. However, this will mean that `POST`ing to `/tools` or `PUT`ting to `/tools/{id}` will auto-generate _both_ tool and version IDs. To avoid that and allow users to use these endpoints with predefined version IDs, further changes to the specs are required. Possibly this will require different tool version schemas for registering tools than for registering versions.

**Comment by uniqueg** [comment]
Changed my mind and will implement this now for consistency and adherence to best "REST" practices. Implementing it later would be a breaking change for downstream applications, so it is better to stabilize the API.
